import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mailConfiguration,authorizedCron,alertMessage,deliverAlerts} from '../lib/solar-alerts.js';
import operations from '../api/operations.js';
const env={SMTP_HOST:'smtp.livemail.co.uk',SMTP_USER:'hello@aesirsolar.co.uk',SMTP_PASSWORD:'fixture',SOLAR_OPERATIONS_EMAIL:'operator@example.com'};
const row=()=>({application_id:randomUUID(),lease_token:randomUUID(),livemode:false,amount_pence:30000,details:{contact:'Fixture <script>',company:'Test only'}});
test('SMTP uses authenticated TLS with bounded deadlines and cannot read files or remote message URLs',()=>{const c=mailConfiguration(env);assert.equal(c.options.secure,true);assert.equal(c.options.port,465);assert.equal(c.options.disableFileAccess,true);assert.equal(c.options.disableUrlAccess,true);assert.throws(()=>mailConfiguration({...env,SMTP_HOST:'attacker.example'}));assert.throws(()=>mailConfiguration({...env,SOLAR_OPERATIONS_EMAIL:'a@b.com\r\nBcc:c@d.com'}));});
test('alert is clearly test or live, has one stable reference and contains no token or applicant-controlled headers',()=>{const r=row(),a=alertMessage(r,env.SOLAR_OPERATIONS_EMAIL),b=alertMessage(r,env.SOLAR_OPERATIONS_EMAIL);assert.equal(a.messageId,b.messageId);assert.match(a.subject,/TEST/);assert.match(a.text,/£250.*£50.*£300/);assert.match(a.text,/solar_operator_queue/);assert.equal(a.html,undefined);assert.doesNotMatch(a.subject,/Fixture/);assert.doesNotMatch(a.text,/accessToken|token_hash|lease_token/);assert.doesNotMatch(alertMessage({...r,livemode:true},env.SOLAR_OPERATIONS_EMAIL).subject,/TEST/);});
function fixture({sendFails=false,ackFails=false}={}){const r=row(),calls=[];let claim=true;return {calls,svc:{rpc:async(name,args)=>{calls.push([name,args]);if(name==='solar_claim_alert'){if(!claim)return null;claim=false;return r;}if(ackFails&&args.p_sent)throw Error('DB unavailable');return true;}},createTransport:()=>({sendMail:async m=>{calls.push(['send',m]);if(sendFails)throw Error('SMTP PRIVATE ERROR');return {accepted:[env.SOLAR_OPERATIONS_EMAIL]};},close:()=>calls.push(['close'])})};}
test('successful SMTP acceptance is recorded once and transport is disposed',async()=>{const f=fixture();assert.deepEqual(await deliverAlerts(f.svc,{livemode:false},{env,limit:3,createTransport:f.createTransport}),{sent:1,failed:0});assert.equal(f.calls.filter(c=>c[0]==='send').length,1);assert.equal(f.calls.find(c=>c[0]==='solar_finish_alert')[1].p_sent,true);assert.equal(f.calls.at(-1)[0],'close');});
test('failed SMTP leaves retryable alert and does not expose raw provider error',async()=>{const f=fixture({sendFails:true});assert.deepEqual(await deliverAlerts(f.svc,{livemode:false},{env,createTransport:f.createTransport}),{sent:0,failed:1});const result=f.calls.find(c=>c[0]==='solar_finish_alert')[1];assert.equal(result.p_sent,false);assert.equal(result.p_uncertain,false);assert.doesNotMatch(JSON.stringify(result),/PRIVATE/);});
test('accepted email with failed database acknowledgement is explicitly uncertain and retryable',async()=>{const f=fixture({ackFails:true});assert.equal((await deliverAlerts(f.svc,{livemode:false},{env,createTransport:f.createTransport})).failed,1);assert.equal(f.calls.filter(c=>c[0]==='solar_finish_alert').at(-1)[1].p_uncertain,true);});
test('cron rejects missing, weak and incorrect bearer secrets before any provider operation',async()=>{const token='x'.repeat(64);assert.equal(authorizedCron({headers:{authorization:'Bearer '+token}},{CRON_SECRET:token}),true);for(const header of [undefined,'Bearer wrong','Bearer '+token+'x'])assert.equal(authorizedCron({headers:{authorization:header}},{CRON_SECRET:token}),false);let code;const res={setHeader(){},status(n){code=n;return this;},json(){return this;},end(){return this;}};await operations({method:'GET',headers:{}},res);assert.equal(code,401);});
